AvaTax4ServiceMax/src/objects/Avalara__c.object
<CustomObject>
    <description>Object to store Avalara Credentials and Avalara options</description>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Country for Origin Address used in Avalara Tax Calcs. Enter 2 or 3 character ISO country code.</inlineHelpText>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_City__c</fullName>
        <inlineHelpText>City for Origin Address to be used in Avalara Tax Calculations</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_Postal_Code__c</fullName>
        <inlineHelpText>Postal or Zip Code for Origin Address to be used in tax Calculations. For US Zip Codes can be Zip5 or Zip9 (Zip + 4)</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_State__c</fullName>
        <inlineHelpText>State or Province for Origin Address to be used in Avalara Tax Calcs. Use 2 character abbreviations as specified by US or Canada Postal Service.</inlineHelpText>
        <label>State/Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_Street__c</fullName>
        <inlineHelpText>Enter up to 3 Street Address lines for the Origin Address to be used in the Avalara Tax Calcs. More lines can be entered, but only the first 3 will be used in tax Calculations.</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Avalara Account</label>
    <nameField>
        <label>Avalara Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Avalara</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AvaTax4ServiceMax/src/classes/AVA_OriginAddressValidation.cls
////////////////////////////////////////////////////////////////////////////////
// Implementation of driver class for Validate Origin Address button handler
// on AvalaraConfig page.  See AVA_OriginAddressValidation.page
// for this one, we point directly to ValidationBase, no middle class
// needed, since Avalara__c object is part of data for base anyway
////////////////////////////////////////////////////////////////////////////////
global with sharing class AVA_OriginAddressValidation
extends AVA_AddressValidationBase
{
    //Constructor for use in automation tax calc
    public AVA_OriginAddressValidation(ApexPages.StandardController controller) 
    {
        avaConfig = AVA_Utilities.FetchCurrentSettings(apCurPage);
    }
    //Constructor for use current page it and fetch current user's config page data
    public AVA_OriginAddressValidation(Id currentPage)
    {
        apCurPage = currentPage;
        avaConfig = AVA_Utilities.FetchCurrentSettings(currentPage);
    }
    // Fech Origin address data from current active setting
    global override void FetchOriginalAddress()
    {
        // parse multi-line OriginStreet__c Entry
        if(null != avaConfig[0].Origin_Street__c)
        {
            List<String> Lines = avaConfig[0].Origin_Street__c.split('\r\n');
        
            Original.Line1 = Lines[0].trim();
            if(Lines.size() > 1)
            {
                Original.Line2 = Lines[1].trim();
            }
            if(Lines.size() > 2)
            {
                Original.Line3 = Lines[2].trim();
            }
        }
       
        Original.City = avaConfig[0].Origin_City__c;
        Original.Region = avaConfig[0].Origin_State__c;
        Original.PostalCode = avaConfig[0].Origin_Postal_Code__c;
        Original.Country = avaConfig[0].Country__c;
    }
    
    //Update origin address in latchupdate and update data of SF data
    global override PageReference UpdateAddress()
    {
        if(avaConfig.size() > 0)    // 0 means we are testing
        {
            update avaConfig[0];
        //    avaConfig[0].Last_Validated__c = datetime.now().format();
         //   Utilities.LatchedUpdate(avaConfig[0]);
        }
        return RedirectPage();
    }
   //fetch validate address from avalara api and update those in sf 
    global override void SetUpdatedAccountAddress(AVA_AddressSvc.ValidAddress addressValidationResult)
    {
        avaConfig[0].Origin_Street__c = addressValidationResult.Line1;
        String strt;
        if(addressValidationResult.Line2 != null)
        {
            strt = addressValidationResult.Line2.trim();
            if(strt.length() > 0)
            {
                avaConfig[0].Origin_Street__c += '\r\n' + strt;
            }
        }
        if(addressValidationResult.Line3 != null)
        {
            strt = addressValidationResult.Line3.trim();
            if(strt.length() > 0)
            {
                avaConfig[0].Origin_Street__c += '\r\n' + strt;
            }
        }
        avaConfig[0].Origin_County__c = addressValidationResult.County;
        avaConfig[0].Origin_City__c = addressValidationResult.City;
        avaConfig[0].Origin_State__c = addressValidationResult.Region;
        avaConfig[0].Origin_Postal_Code__c = addressValidationResult.PostalCode; 
        avaConfig[0].Country__c = addressValidationResult.Country;       
    }
}